apiVersion: v2
name: logging
description: Logging stack (ELK) for Aegonish Blog
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
  - name: filebeat
    version: "8.5.1"
    repository: "https://helm.elastic.co"
  - name: kibana
    version: "8.5.1"
    repository: "https://helm.elastic.co"
