apiVersion: v2
name: aegonish-blog
description: Local umbrella chart
type: application
version: 0.1.0

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"

  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"

  - name: mongo
    version: 0.1.0
    repository: "file://charts/mongo"
